export const SLOGANS = [
  {
    key: 1,
    delay: 0.2,
    className: "self-start",
    title: "CLEAR INTERFACES",
    description: "언제나 보다 나은 인터페이스를 고민하고 구축합니다.",
    tooltipPosition: "left-10",
    emoji: null,
    pointer: true,
  },
  {
    key: 2,
    delay: 0.5,
    className: "self-center",
    title: "EFFICIENT WORKFLOWS",
    description: "때에 맞는 가장 효율적인 워크플로우를 채택합니다.",
    tooltipPosition: "left-1/2 transform -translate-x-1/2",
    emoji: "🔧",
    pointer: false,
  },
  {
    key: 3,
    delay: 0.7,
    className: "self-end",
    title: "MAINTAINABLE FRONTEND",
    description: "보이는게 다가 아닌 유지보수 가능한 프론트엔드를 구축합니다.",
    tooltipPosition: "right-10",
    emoji: null,
    pointer: false,
  },
  {
    key: 4,
    delay: 0.9,
    className: "self-start",
    title: "HARD WORKS, PAYS OFF",
    description: "열정과 비례하는 결과를 창출합니다.",
    tooltipPosition: "left-10",
    emoji: "😎",
    emojiPosition: "end",
    pointer: false,
  },
];
